
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: NODE_ENV=production npm run build
      
    - name: Copy built files to deployment directory
      run: |
        mkdir -p deploy
        cp -r dist/public/* deploy/
        cp client/public/_redirects deploy/ 2>/dev/null || true
        cp client/public/404.html deploy/ 2>/dev/null || true
        # Ensure assets are in the right place
        if [ -d "assets" ]; then
          cp -r assets deploy/
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        cname: false
