
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Fresh deployment with icon verification
      run: |
        # Complete clean slate
        rm -rf dist/ node_modules/.cache/ deploy/
        
        # Fresh build
        NODE_ENV=production npm run build
        
        # Verify icons are in build
        echo "Checking for service icons..."
        if grep -r "TrendingUp\|UserCheck\|Users" dist/public/assets/*.js; then
          echo "✅ Service icons verified in build"
        else
          echo "❌ Service icons missing in build"
          exit 1
        fi
        
        # Create deployment
        mkdir -p deploy
        cp -r dist/public/* deploy/
        cp _redirects deploy/ 2>/dev/null || true
        cp 404.html deploy/ 2>/dev/null || true
        
        # Force browser cache refresh
        echo "<!-- Forced update: $(date +%s) -->" >> deploy/index.html
        
        # Show deployment verification
        echo "=== DEPLOYMENT CONTENTS ==="
        ls -la deploy/assets/
        echo "=== ICON VERIFICATION ==="
        grep -o "TrendingUp\|UserCheck\|Users" deploy/assets/*.js | head -5
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        cname: false
