
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Clear cache and build fresh
      run: |
        rm -rf dist/ node_modules/.cache/
        NODE_ENV=production npm run build
      
    - name: Copy built files to deployment directory
      run: |
        mkdir -p deploy
        cp -r dist/public/* deploy/
        cp _redirects deploy/ 2>/dev/null || true
        cp 404.html deploy/ 2>/dev/null || true
        # Add timestamp to force update
        echo "<!-- Build: $(date) -->" >> deploy/index.html
        # Show what we're deploying
        echo "Deploying assets:"
        ls -la deploy/assets/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        cname: false
